name: Advon Analytics
markdown: kramdown
pygments: false
excerpt_separator: <!--more-->
paginate: 3
paginate_path: "blog/page:num"
permalink: /blog/:year/:month/:day/:title.html
url: https://advonanalytics.com
enforce_ssl: advonanalytics.com

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
